#!/bin/sh 
set -e

if test -z $MAX_CLIENT_CONNECTED; then
   sed -i '/limit_conn/d' /etc/nginx/conf.d/default.conf.template;
fi 

envsubst < /etc/nginx/conf.d/default.tmpl > /etc/nginx/conf.d/default.conf 

echo "Starting nginx..."

nginx -g 'daemon off;'
