#!/bin/bash
set -e

# Defaults
apply_default () { export $1=${!1:-"$2"}; }

apply_default REMOTE_PROTO 'https'
apply_default REMOTE_HOST ''
apply_default REMOTE_URI ''
apply_default CACHE_TTL '5m'
apply_default MAX_CACHE_SIZE '10g'
apply_default MAX_CLIENT_CONNECTED ''
apply_default CACHE_LOCK_TIMEOUT '10s'
apply_default CACHE_INACTIVE '3M'
apply_default REWRITE_HOST $REMOTE_HOST
apply_default MODE 'cache'

# Preserve nginx variables
for key in server_name upstream_cache_status http_user_agent uri is_args args; do
  export $key=\$$key
done

generateTemplate() {
  template=$1
  dst=$2

  if [ -z $MAX_CLIENT_CONNECTED ] ; then
    sed -i '/limit_conn/d' $template;
  fi

  if [ -z $REWRITE_URL ] ; then
    sed -i '/sub_filter/d' $template;
  fi

  case $MODE in
    cache)
      sed -i '/MODE_STORE/d' $template;
    ;;
    store)
      sed -i '/MODE_CACHE/d' $template;
    ;;
  esac

  envsubst < $template > $dst
}

generateTemplate /app/proxy.conf /etc/nginx/proxy.conf
generateTemplate /app/default.conf /etc/nginx/sites-enabled/default

envsubst < /app/banner

nginx -g 'daemon off;'
